module.exports = {
  content: ["_site/**/*.html", "_site/**/*.js"],
  css: ["_site/assets/css/*.css"],
  output: "_site/assets/css/",
  skippedContentGlobs: ["_site/assets/**/*.html"],
  defaultExtractor: (content) => content.match(/[\w-/:]+(?<!:)/g) || [],
  safelist: {
    standard: [
      "collapse",
      "collapsing",
      "show",
      "dropdown-menu",
      "dropdown-item",
      "table",
      "table-dark",
      "table-hover",
      "table-responsive",
      "af-tooltip",
      "af-popover",
      "font-weight-bold",
      "font-weight-medium",
      "font-weight-lighter",
      "medium-zoom-overlay",
      "medium-zoom-image--opened",
    ],
    greedy: [
      /^(sm|md|lg|xl|2xl):/,
      /^dark:/,
      /^hover:/,
      /^focus:/,
      /slate/,
      /serif/,
      /sans/,
      /mono/,
      /tech-pill/,
      /project-card/,
      /hero-/,
    ],
  },
};
